name: snusyoulooseflutter
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  http: ^1.1.0
  provider: ^6.1.1
  flutter_redux: ^0.10.0
  redux_thunk: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - Assets/Images/
    - Assets/Icons/
